# Generated by Django 3.2.7 on 2022-09-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20220928_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
